### ISSUE TITLE
where is preprocess3 module?

### ISSUE THREAD

**Issue by xuzhuojia** [jefferyYu/WSDM18_codes#1]
train_transfer_model5.py uses preprocess3 module to convert raw data to SNLI, but where is preprocess3? And what is aux_labels ?  When I train PI task through train_transfer_model5, is that necessary to have aux_labels ?

**Comment by jefferyYu** [comment]
Hi,

Sorry for forgetting to upload the "preprocess3.py" file, and now you can find it in the repo. 

The aux_labels refers to the domain label, i.e., source domain or target domain in our case. 

For the aux_labels, the reason to put it in our codes is that we originally wanted to use gradient reversal layer to implement the adversarial part. But anyway, in the current version, it is not necessary to have aux_labels.

**Comment by xuzhuojia** [comment]
Thank you. That's a big help.
